### ISSUE TITLE
TypeError when extracting features from deleted revisions

### ISSUE THREAD

**Issue by he7d3r** [halfak/Revision-Scoring#14]
As reported by Danilo [on Trello](https://trello.com/c/LRNL5gLv), if we attempting to extract features from a deleted revision such as
https://pt.wikipedia.org/wiki/?diff=40837381&uselang=en
an error occurs:
```
Extracting features for http://pt.wikipedia.org/wiki/?oldid=40837381&diff=prev
Traceback (most recent call last):
  File "demonstrate_extractor.py", line 72, in <module>
    features = api_extractor.extract(40837381, extractors)
  File "mypath/Revision-Scoring/revscores/api_extractor.py", line 19, in extract
    return [solve(feature, cache) for feature in features]
  File "mypath/Revision-Scoring/revscores/api_extractor.py", line 19, in <listcomp>
    return [solve(feature, cache) for feature in features]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in solve
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in <listcomp>
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in solve
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in <listcomp>
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in solve
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in <listcomp>
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in solve
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 111, in <listcomp>
    for dependency in dependencies]
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 115, in solve
    value = dependent(*args)
  File "mypath/Revision-Scoring/revscores/util/dependencies.py", line 20, in __call__
    return self.f(*args, **kwargs)
  File "mypath/Revision-Scoring/revscores/datasources/revision_diff.py", line 16, in revision_diff
    b = tokenizer.tokenize(revision_text)
  File "/home/helder/.mypyvenv/lib/python3.4/site-packages/deltas/tokenizers/wikitext_split.py", line 10, in tokenize
    text
  File "/usr/lib/python3.4/re.py", line 206, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

**Comment by halfak** [comment]
This should be resolved now.
