### ISSUE TITLE
AttributeError: type object 'Namespace' has no attribute 'from_doc'

### ISSUE THREAD

**Issue by he7d3r** [halfak/Revision-Scoring#29]
I just updated my local copy of the repo and got this when running the tests:
```python
$ nosetests
..E...........................................................
======================================================================
ERROR: revscores.datasources.tests.test_namespaces.test_namespaces
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/helder/.mypyvenv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/helder/Revision-Scoring/revscores/datasources/tests/test_namespaces.py", line 39, in test_namespaces
    nses = namespaces(fake_si_doc)
  File "/home/helder/Revision-Scoring/revscores/dependent.py", line 18, in __call__
    return self.process(*args, **kwargs)
  File "/home/helder/Revision-Scoring/revscores/datasources/namespaces.py", line 18, in process
    namespaces[ns_id] = mw.Namespace.from_doc(ns_doc, aliases=aliases)
nose.proxy.AttributeError: type object 'Namespace' has no attribute 'from_doc'
-------------------- >> begin captured logging << --------------------
revscores.dependent: DEBUG: Executing <namespaces>.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 62 tests in 2.547s

FAILED (errors=1)
```

**Comment by he7d3r** [comment]
This error happens since 2d6b636b16b7760a5f904c3b83b835251d638b8b and was not happening at 59c562f2e4c6d3b6e6a4e96344fdcffc993741a1.

**Comment by halfak** [comment]
I just ran the tests and they passed.  You might need to update mediawiki-utilities.

"pip install mediawiki-utilities --upgrade"

**Comment by he7d3r** [comment]
Indeed!
```
$ pip install mediawiki-utilities --upgrade
Downloading/unpacking mediawiki-utilities from https://pypi.python.org/packages/source/m/mediawiki-utilities/mediawiki-utilities-0.4.9.tar.gz#md5=edc2aed61fba3e76550f09a0012d04c4
  Downloading mediawiki-utilities-0.4.9.tar.gz (49kB): 49kB downloaded
  Running setup.py (path:/home/helder/.mypyvenv/build/mediawiki-utilities/setup.py) egg_info for package mediawiki-utilities
    
Requirement already up-to-date: argparse>=1.1 in /home/helder/.mypyvenv/lib/python3.4/site-packages (from mediawiki-utilities)
Requirement already up-to-date: requests>=2.0.1 in /home/helder/.mypyvenv/lib/python3.4/site-packages (from mediawiki-utilities)
Requirement already up-to-date: pymysql>=0.6.2 in /home/helder/.mypyvenv/lib/python3.4/site-packages (from mediawiki-utilities)
Installing collected packages: mediawiki-utilities
  Found existing installation: mediawiki-utilities 0.4.7
    Uninstalling mediawiki-utilities:
      Successfully uninstalled mediawiki-utilities
  Running setup.py install for mediawiki-utilities
    
Successfully installed mediawiki-utilities
Cleaning up...
```
and then
```
$ nosetests
..............................................................
----------------------------------------------------------------------
Ran 62 tests in 2.569s

OK
```
