### ISSUE TITLE
ImportError (cannot import name 'WikitextSplit')

### ISSUE THREAD

**Issue by he7d3r** [halfak/Revision-Scoring#66]
```python
(3.4) helder@std:~/projects/revscoring
$nosetests
EE....EE...
======================================================================
ERROR: Failure: ImportError (cannot import name 'WikitextSplit')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/helder/projects/revscoring/revscoring/datasources/__init__.py", line 1, in <module>
    from .contiguous_segments_added import contiguous_segments_added
  File "/home/helder/projects/revscoring/revscoring/datasources/contiguous_segments_added.py", line 4, in <module>
    from .revision_diff import revision_diff
  File "/home/helder/projects/revscoring/revscoring/datasources/revision_diff.py", line 4, in <module>
    from deltas.tokenizers import WikitextSplit
ImportError: cannot import name 'WikitextSplit'

======================================================================
ERROR: Failure: ImportError (cannot import name 'WikitextSplit')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/helder/projects/revscoring/revscoring/features/__init__.py", line 2, in <module>
    from .added_badwords_ratio import added_badwords_ratio
  File "/home/helder/projects/revscoring/revscoring/features/added_badwords_ratio.py", line 2, in <module>
    from .proportion_of_badwords_added import proportion_of_badwords_added
  File "/home/helder/projects/revscoring/revscoring/features/proportion_of_badwords_added.py", line 2, in <module>
    from .badwords_added import badwords_added
  File "/home/helder/projects/revscoring/revscoring/features/badwords_added.py", line 3, in <module>
    from ..datasources import contiguous_segments_added
  File "/home/helder/projects/revscoring/revscoring/datasources/__init__.py", line 1, in <module>
    from .contiguous_segments_added import contiguous_segments_added
  File "/home/helder/projects/revscoring/revscoring/datasources/contiguous_segments_added.py", line 4, in <module>
    from .revision_diff import revision_diff
  File "/home/helder/projects/revscoring/revscoring/datasources/revision_diff.py", line 4, in <module>
    from deltas.tokenizers import WikitextSplit
ImportError: cannot import name 'WikitextSplit'

======================================================================
ERROR: Failure: ImportError (cannot import name 'WikitextSplit')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/helder/projects/revscoring/revscoring/scorers/tests/test_scorer.py", line 5, in <module>
    from ...features import badwords_added, misspellings_added
  File "/home/helder/projects/revscoring/revscoring/features/__init__.py", line 2, in <module>
    from .added_badwords_ratio import added_badwords_ratio
  File "/home/helder/projects/revscoring/revscoring/features/added_badwords_ratio.py", line 2, in <module>
    from .proportion_of_badwords_added import proportion_of_badwords_added
  File "/home/helder/projects/revscoring/revscoring/features/proportion_of_badwords_added.py", line 2, in <module>
    from .badwords_added import badwords_added
  File "/home/helder/projects/revscoring/revscoring/features/badwords_added.py", line 3, in <module>
    from ..datasources import contiguous_segments_added
  File "/home/helder/projects/revscoring/revscoring/datasources/__init__.py", line 1, in <module>
    from .contiguous_segments_added import contiguous_segments_added
  File "/home/helder/projects/revscoring/revscoring/datasources/contiguous_segments_added.py", line 4, in <module>
    from .revision_diff import revision_diff
  File "/home/helder/projects/revscoring/revscoring/datasources/revision_diff.py", line 4, in <module>
    from deltas.tokenizers import WikitextSplit
ImportError: cannot import name 'WikitextSplit'

======================================================================
ERROR: Failure: ImportError (cannot import name 'WikitextSplit')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/helder/env/3.4/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/helder/projects/revscoring/revscoring/scorers/tests/test_svc.py", line 8, in <module>
    from ...features import Feature
  File "/home/helder/projects/revscoring/revscoring/features/__init__.py", line 2, in <module>
    from .added_badwords_ratio import added_badwords_ratio
  File "/home/helder/projects/revscoring/revscoring/features/added_badwords_ratio.py", line 2, in <module>
    from .proportion_of_badwords_added import proportion_of_badwords_added
  File "/home/helder/projects/revscoring/revscoring/features/proportion_of_badwords_added.py", line 2, in <module>
    from .badwords_added import badwords_added
  File "/home/helder/projects/revscoring/revscoring/features/badwords_added.py", line 3, in <module>
    from ..datasources import contiguous_segments_added
  File "/home/helder/projects/revscoring/revscoring/datasources/__init__.py", line 1, in <module>
    from .contiguous_segments_added import contiguous_segments_added
  File "/home/helder/projects/revscoring/revscoring/datasources/contiguous_segments_added.py", line 4, in <module>
    from .revision_diff import revision_diff
  File "/home/helder/projects/revscoring/revscoring/datasources/revision_diff.py", line 4, in <module>
    from deltas.tokenizers import WikitextSplit
ImportError: cannot import name 'WikitextSplit'

----------------------------------------------------------------------
Ran 11 tests in 2.422s

FAILED (errors=4)
```

**Comment by he7d3r** [comment]
Never mind.
`$git rebase upstream/master`
fixed the issue for me (I think I was missing e381ce6 locally).
